"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_act_fn', 'simple_make_mlp', 'ResidualMLPLayer', 'Simple_MLPlayer', 'make_modern_mlp', 'one_step_forward',
           'compute_ce_loss', 'compute_mse_loss', 'train_step', 'validate', 'forward_and_extract_activities',
           'jpc_init_activities_with_ffwd', 'init_activities_from_normal_ffwd', 'clip_array_by_row', 'mse_energy',
           'cos_similar_energy', 'compute_energy', 'jpc_pc_energy_fn', 'perform_inference', 'plot_energy_history',
           'jpc_neg_activity_grad', 'jpc_solve_inference', 'jpc_steady_state_event_with_timeout',
           'init_activities_as_ffwd_plus_noise_real', 'pc_training_step', 'pc_final_inference_BP',
           'pc_final_inference_ODE', 'validate_generation']

# %% ../nbs/00_core.ipynb 2
import os
import pickle
import warnings
from pathlib import Path
import matplotlib.pyplot as plt
import equinox as eqx
import equinox.nn as nn

import jax
import jax.numpy as jnp
from jax.tree_util import tree_leaves, tree_map
import numpy as np
import optax
import torch
import torchvision
import torchaudio
from torch.utils.data import Dataset, DataLoader, Subset
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
from diffrax import (AbstractSolver, AbstractStepSizeController, Event, Heun,
                    ODETerm, PIDController, SaveAt, diffeqsolve)
from optimistix import rms_norm
from typing import Any, Callable, List, Optional, Tuple, Dict, Literal
# if is called in a notebook, use tqdm.notebook
from jaxtyping import PRNGKeyArray, PyTree, ArrayLike, Scalar, Array
from functools import partial
from IPython import get_ipython
from data_creator import get_mnist_loaders

if get_ipython() is not None:
    from tqdm.notebook import tqdm
else:
    from tqdm import tqdm


# %% ../nbs/00_core.ipynb 4
def get_act_fn(name: str) -> Callable:
    _ACT_FNS = [
        "linear", "tanh", "hard_tanh", "relu", "leaky_relu", "gelu", "selu", "silu"
    ]
    if name == "linear":
        return nn.Identity()
    elif name == "tanh":
        return jnp.tanh
    elif name == "hard_tanh":
        return jax.nn.hard_tanh
    elif name == "relu":
        return jax.nn.relu
    elif name == "leaky_relu":
        return jax.nn.leaky_relu
    elif name == "gelu":
        return jax.nn.gelu
    elif name == "selu":
        return jax.nn.selu
    elif name == "silu":
        return jax.nn.silu
    else:
        raise ValueError(f"""
                Invalid activation function ID. Options are {_ACT_FNS}.
        """)
    

def simple_make_mlp(key: PRNGKeyArray, 
        input_dim: int, 
        width: int,
        depth: int, 
        output_dim: int, 
        act_fn: str, 
        use_layer_norm: bool = False,
        use_bias: bool = False,):
    subkeys = jax.random.split(key, depth + 1)
    layers = []
    for i in range(depth):
        # First layer: no activation, Last layer: no activation, Hidden layers: activation
        is_first = i == 0
        is_last = i == depth - 1
        act_fn_l = nn.Identity() if (is_first or is_last) else get_act_fn(act_fn)
        
        in_dim = input_dim if i == 0 else width
        out_dim = output_dim if i == depth - 1 else width

        linear = nn.Linear(in_dim, out_dim, use_bias=use_bias, key=subkeys[i])
        layers.append(eqx.nn.Sequential([
            nn.Lambda(act_fn_l), 
            linear, 
            nn.LayerNorm(out_dim) if use_layer_norm else nn.Identity()
        ]))

    return layers

# %% ../nbs/00_core.ipynb 6
class ResidualMLPLayer(eqx.Module):
    linear: nn.Linear
    ln_pre: eqx.Module
    ln_post: eqx.Module
    act: eqx.Module
    dropout: nn.Dropout
    ln_position: Literal["pre", "post"]
    use_residual: bool

    def __init__(
        self,
        key: PRNGKeyArray,
        in_dim: int,
        out_dim: int,
        act_module: eqx.Module,
        use_layer_norm: bool,
        use_bias: bool,
        ln_position: Literal["pre", "post"],
        dropout_rate: float = 0.0,
        use_residual: bool = True,
        init_method: Literal["kaiming", None] = None,
        init_gain: float = 1.0,
    ):
        self.linear = nn.Linear(in_dim, out_dim, use_bias=use_bias, key=key)
        self.act = act_module
        self.ln_position = ln_position

        # Residual check
        if use_residual and (in_dim == out_dim):
            self.use_residual = True
        elif use_residual and (in_dim != out_dim):
            raise ValueError(
                f"Residual connection requires in_dim == out_dim, "
                f"current in_dim: {in_dim}, out_dim: {out_dim}"
            )
        else:
            self.use_residual = False

        # LayerNorm modules
        if use_layer_norm:
            self.ln_pre = nn.LayerNorm(in_dim)
            self.ln_post = nn.LayerNorm(out_dim)
        else:
            self.ln_pre = nn.Identity()
            self.ln_post = nn.Identity()

        # Dropout module (no-op if rate == 0.0 at runtime)
        # Remember you must pass a key when calling this layer under jit.
        self.dropout = nn.Dropout(p=dropout_rate)

        if init_method == "kaiming":
            self.kaiming_init(key, gain=init_gain)

    def __call__(self, x, *, key: PRNGKeyArray | None = None, inference: bool = False):
        """
        x: input tensor
        key: PRNG key for dropout (required if dropout_rate > 0 and not inference)
        inference: if True, disables dropout
        """
        residual = x if self.use_residual else None

        if self.ln_position == "pre":
            h = self.ln_pre(x)
            h = self.linear(h)
            h = self.act(h)
        elif self.ln_position == "post":
            h = self.linear(x)
            h = self.act(h)
            h = self.ln_post(h)
        else:  # should not happen if type-checked
            raise ValueError(f"Invalid ln_position: {self.ln_position!r}")

        # Apply dropout after activation (and LN in post-LN case is already included above)
        # eqx.nn.Dropout expects key and inference flag at call time.
        h = self.dropout(h, key=key, inference=inference)

        if residual is not None:
            return residual + h
        else:
            return h
        
    def kaiming_init(self, key: PRNGKeyArray, gain: float = 1.0):
        """
        Reinitialize the linear layer's weight using Kaiming (He) initialization.
        
        Args:
            key: PRNG key for random initialization
            gain: scaling factor for the initialization (default 1.0)
        """
        # Kaiming initialization: scale = sqrt(1.0 / fan_in)
        in_features = self.linear.in_features
        scale = jnp.sqrt(1.0 / in_features)
        
        # Get the current weight shape and dtype
        w = self.linear.weight
        
        # Generate new weights with Kaiming initialization
        new_w = jax.random.normal(key, w.shape, dtype=w.dtype) * scale * gain
        
        # Update weight using eqx.tree_at
        self.linear = eqx.tree_at(lambda m: m.weight, self.linear, new_w)
        
        # Reset bias to zero if it exists
        if self.linear.use_bias:
            self.linear = eqx.tree_at(
                lambda m: m.bias, 
                self.linear, 
                jnp.zeros_like(self.linear.bias)
            )


class Simple_MLPlayer(eqx.Module):
    """Block: x -> Act -> Linear -> (optional) LayerNorm.

    This reproduces the original Sequential:
        [nn.Lambda(act_fn_l), linear, LayerNorm or Identity]
    """

    linear: nn.Linear
    ln: eqx.Module
    act: eqx.Module

    def __init__(
        self,
        key: PRNGKeyArray,
        in_dim: int,
        out_dim: int,
        act_module: eqx.Module,
        use_layer_norm: bool,
        use_bias: bool,
        init_method: Literal["kaiming", None] = None,
        init_gain: float = 1.0,
    ):
        self.linear = nn.Linear(in_dim, out_dim, use_bias=use_bias, key=key)
        self.act = act_module
        self.ln = nn.LayerNorm(out_dim) if use_layer_norm else nn.Identity()

        if init_method == "kaiming":
            self.kaiming_init(key, gain=init_gain)

    def __call__(
        self,
        x: jnp.ndarray,
        *,
        key: PRNGKeyArray | None = None,
        inference: bool = False,
    ) -> jnp.ndarray:
        # key and inference are accepted for API compatibility but ignored.
        x = self.act(x)      # nn.Lambda(act_fn_l)
        x = self.linear(x)   # Linear
        x = self.ln(x)       # LayerNorm(out_dim) or Identity
        return x
    
    def kaiming_init(self, key: PRNGKeyArray, gain: float = 1.0):
        """
        Reinitialize the linear layer's weight using Kaiming (He) initialization.
        
        Args:
            key: PRNG key for random initialization
            gain: scaling factor for the initialization (default 1.0)
        """
        # Kaiming initialization: scale = sqrt(1.0 / fan_in)
        in_features = self.linear.in_features
        scale = jnp.sqrt(1.0 / in_features)
        
        # Get the current weight shape and dtype
        w = self.linear.weight
        
        # Generate new weights with Kaiming initialization
        new_w = jax.random.normal(key, w.shape, dtype=w.dtype) * scale * gain
        
        # Update weight using eqx.tree_at
        self.linear = eqx.tree_at(lambda m: m.weight, self.linear, new_w)
        
        # Reset bias to zero if it exists
        if self.linear.use_bias:
            self.linear = eqx.tree_at(
                lambda m: m.bias, 
                self.linear, 
                jnp.zeros_like(self.linear.bias)
            )


def make_modern_mlp(
    key: PRNGKeyArray,
    input_dim: int,
    width: int,
    depth: int,
    output_dim: int,
    act_fn: str,
    use_layer_norm: bool = False,
    use_bias: bool = False,
    ln_position: Literal["pre", "post"] = "pre",
    dropout_rate: float = 0.0,
    use_residual_blocks: bool = False,
    init_method: Literal["kaiming", None] = None,
    init_gain: float = 1.0,
):
    """
    Build an MLP as a stack of blocks.

    If use_residual_blocks is True:
        ResidualMLPLayer is used for each layer.

        For each layer:
            - ln_position == "pre":
                x -> LN -> Linear -> Act -> Dropout -> (+ x if dims match)
            - ln_position == "post":
                x -> Linear -> Act -> LN -> Dropout -> (+ x if dims match)

        Residual connection is only applied when in_dim == out_dim for that layer.
        Here, the last layer uses no residual.

    If use_residual_blocks is False:
        Simple_MLPlayer is used for each layer:
            x -> Act -> Linear -> (optional) LayerNorm
        (no residual, no dropout).
    """
    subkeys = jax.random.split(key, depth)
    layers = []

    for i in range(depth):
        is_first = i == 0
        is_last = i == depth - 1

        in_dim = input_dim if is_first else width
        out_dim = output_dim if is_last else width

        # First and last layer: no activation, hidden layers: chosen activation
        act_module = nn.Identity() if (is_first or is_last) else get_act_fn(act_fn)

        if use_residual_blocks:
            layer = ResidualMLPLayer(
                key=subkeys[i],
                in_dim=in_dim,
                out_dim=out_dim,
                act_module=act_module,
                use_layer_norm=use_layer_norm,
                use_bias=use_bias,
                ln_position=ln_position,
                dropout_rate=dropout_rate,
                # last layer: no residual; others: residual (if dims match)
                use_residual=False if (is_last or is_first) else True,
                init_method=init_method,
                init_gain=init_gain,
            )
        else:
            layer = Simple_MLPlayer(
                key=subkeys[i],
                in_dim=in_dim,
                out_dim=out_dim,
                act_module=act_module,
                use_layer_norm=use_layer_norm,
                use_bias=use_bias,
            )

        layers.append(layer)

    return layers

# %% ../nbs/00_core.ipynb 15
@eqx.filter_jit
def one_step_forward(model, x, key, *, inference: bool = False):
    keys = jax.random.split(key, len(model))
    for layer, k in zip(model, keys):
        # batched: x has shape [batch, feat]
        vlayer = eqx.filter_vmap(lambda x: layer(x, key=k, inference=inference), in_axes=0, out_axes=0)
        x = vlayer(x)
    return x

# %% ../nbs/00_core.ipynb 19
# Define loss function
def compute_ce_loss(model, x, y, key, inference: bool = False):
    logits = one_step_forward(model, x, key=key, inference=inference)
    # return optax.softmax_cross_entropy_with_integer_labels(logits, y).mean()
    return optax.softmax_cross_entropy(logits, y).mean()

def compute_mse_loss(model, x, y, key, inference: bool = False):
    logits = one_step_forward(model, x, key=key, inference=inference)
    
    return jnp.mean((logits - y) ** 2)


# Define update step
@eqx.filter_jit
def train_step(model, optimizer, opt_state, x, y, key, loss_fn = compute_ce_loss):
    loss, grads = eqx.filter_value_and_grad(loss_fn)(model, x, y, key=key, inference=False)
    updates, opt_state = optimizer.update(grads, opt_state, eqx.filter(model, eqx.is_array))
    model = eqx.apply_updates(model, updates)
    return {'model': model, 
            'opt_state': opt_state, 
            'loss': loss,
            'grads': grads
        }


def validate(model, data_loader, key, loss_fn = compute_ce_loss):
    total_loss = 0.0
    num_batches = 0
    preds = []
    ys = []
    for images, labels in data_loader:
        # Convert torch tensors to jax arrays
        x = jnp.array(images.numpy())
        y = jnp.array(labels.numpy())
        preds.append(one_step_forward(model, x, key=key, inference=True))
        ys.append(y)
        loss = loss_fn(model, x, y, key=key, inference=True)
        total_loss += loss
        num_batches += 1
    
    # compute accuracy
    acc = jnp.mean(jnp.concatenate(preds).argmax(axis=-1) == jnp.concatenate(ys).argmax(axis=-1))
    avg_loss = total_loss / num_batches
    return avg_loss, acc


# %% ../nbs/00_core.ipynb 25
def forward_and_extract_activities(
    model: List, x, key, *, inference: bool = False
):
    """
    Apply a list of layers (ResidualMLPLayer or Simple_MLPlayer)
    to a batched input x and return the activations after each layer.

    Args:
        model: list of layers, each with __call__(x_single, *, key, inference).
        x: array of shape (batch, feat_in) for the first layer.
        key: PRNGKey for stochastic layers (dropout). One subkey per layer.
        inference: if True, disable dropout inside layers.

    Returns:
        activations: list of arrays; activations[i] is the output of layer i
                        with shape (batch, feat_i).
    """
    keys = jax.random.split(key, len(model))
    activations = []
    h = x

    for layer, k in zip(model, keys):
        # vmap over batch dimension
        vlayer = eqx.filter_vmap(lambda x_single: layer(x_single, key=k, inference=inference), in_axes=0, out_axes=0)
        h = vlayer(h)
        activations.append(h)

    return activations


# def forward_and_extract_activites(fs: list[Callable], x: ArrayLike):
#     '''
#         Applies input to a list that is a sequence of functions/layers,
#         and returns a list of outputs at each step.
#     '''
#     f, *fs = fs
#     # Need to vmap each layer just like in one_step_forward
#     y = eqx.filter_vmap(f, in_axes=0, out_axes=0)(x)
#     return [y] + (forward_and_extract_activites(fs, y) if len(fs) > 0 else [])

# %% ../nbs/00_core.ipynb 26
def jpc_init_activities_with_ffwd(
        model: PyTree[Callable],
        input: ArrayLike,
) -> PyTree[Array]:

    L = len(model)
    z1 = jax.vmap(model[0])(input)

    activities = [z1]
    for l in range(1, L):
        zl = jax.vmap(model[l])(activities[l - 1])
        activities.append(zl)
    return activities

# %% ../nbs/00_core.ipynb 34
def init_activities_from_normal_ffwd(
    key: PRNGKeyArray, 
    model: List[Callable], 
    input_shape: Tuple[int, ...],  # Just the shape, not actual data
    sigma: Scalar = 0.05,
    inference: bool = False,
    include_input: bool = True,  # include input for unsupervised inference or validation
) -> List[Array]:
    """Initialize activities by random."""
    batch_size, *input_dims = input_shape
    
    # Create random input
    random_input = sigma * jax.random.normal(key, input_shape)
    
    # Forward pass to get activity shapes
    activities_clean = forward_and_extract_activities(model, random_input, key=key, inference=inference)
    
    # Add noise to each activity
    random_keys = jax.random.split(key, len(activities_clean))
    random_activities = [
        sigma * jax.random.normal(k, act.shape)
        for act, k in zip(activities_clean, random_keys)
    ]
    if include_input:
        random_activities.insert(0, random_input)
    return random_activities

# %% ../nbs/00_core.ipynb 40
def clip_array_by_row(energy_arr, max_norm=1.0, ord=None):
    '''
    To clip each row vector of energy_arr to have maximum norm of max_norm.
    '''
    row_norms = jnp.linalg.norm(energy_arr, axis=-1, ord=ord, keepdims=True) 
    scale_factors = jnp.minimum(1.0, max_norm / (row_norms + 1e-8))  
    return energy_arr * scale_factors  

# %% ../nbs/00_core.ipynb 41
def mse_energy(prev_acts, curr_acts):
    # 将在接下来的compute_energy中除以batch_size
    # 这样做的原因是不希望mean掉feature dimensions
    err = prev_acts - curr_acts
    return 0.5 * (jnp.mean(err ** 2, axis = -1)).sum()  


def cos_similar_energy(prev_acts, curr_acts):
    """
    Compute energy based on cosine similarity.
    Energy is higher when vectors are less similar.
    Returns: 1 - cosine_similarity, where 0 means perfect alignment.
    """
    # Normalize vectors
    prev_norm = prev_acts / (jnp.linalg.norm(prev_acts, axis=-1, keepdims=True) + 1e-8)
    curr_norm = curr_acts / (jnp.linalg.norm(curr_acts, axis=-1, keepdims=True) + 1e-8)
    
    # Compute cosine similarity
    cos_sim = (prev_norm * curr_norm).sum(axis=-1)
    
    # Convert to energy (1 - similarity, so dissimilarity)
    energy = (1 - jnp.abs(cos_sim)).sum()  # abs makes the opppsite direction also good, so this is a sort of disagreement
    
    return energy



def compute_energy(model: List[Callable], activations: List[ArrayLike], key: PRNGKeyArray, y: ArrayLike, x: ArrayLike = None, ener_fn: Callable = mse_energy, loss_fn: Callable = mse_energy, inference: bool = True) -> List[ArrayLike]:
    '''
    energy = (previous layer's activations - current layer's activations) ** 2
    '''
    energies = []
    key, layer0_key = jax.random.split(key)
    vlayer0 = eqx.filter_vmap(
        lambda x_single: model[0](x_single, key=layer0_key, inference=inference), 
        in_axes=0, out_axes=0
    )
    if x == None:
        if len(activations) == len(model) + 1:  # with input
            x, * activations = activations
        else:
            raise NotImplementedError("x must be provided")
    
    energies.append(ener_fn(activations[0], vlayer0(x)))  # (h1 - f(x)) ** 2
    for idx in range(1, len(model)-1):
        key, layer_key = jax.random.split(key)
        vlayer = eqx.filter_vmap(lambda x_single: model[idx](x_single, key=layer_key, inference=inference), in_axes=0, out_axes=0)
        energies.append(ener_fn(activations[idx], vlayer(activations[idx-1])))

    
    # energies.append(0.5 * ((y - activations[-1]) ** 2).sum())  # (y - f(h_last))
    # another way to compute output layer error
    key, last_key = jax.random.split(key)
    vlayer_last = eqx.filter_vmap(
        lambda x_single: model[-1](x_single, key=last_key, inference=inference), 
        in_axes=0, out_axes=0
    )

    if y == None:
        batch_size = x.shape[0]
        energies = [e / batch_size for e in energies]
        return energies
    else:
        # eL = y - vlayer_last(activations[-2])
        energies.append(loss_fn(vlayer_last(activations[-2]), y))  # (y - f(h_last))

        batch_size = y.shape[0]
        energies = [e / batch_size for e in energies]
        return energies


# %% ../nbs/00_core.ipynb 42
def jpc_pc_energy_fn(
        params: Tuple[PyTree[Callable], Optional[PyTree[Callable]]],
        activities: PyTree[ArrayLike],
        y: ArrayLike,
        x: Optional[ArrayLike] = None,
        record_layers: bool = False
) -> Scalar | Array:

    """
    WARNINIG: Cannot handle random activations for now
    """
    # if x is None:
    #     raise NotImplementedError("becau")
    model, skip_model = params

    # if x == None:
    #     if len(activations) == len(model) + 1:  # with input
    #         x, * activations = activations
    #     else:
    #         raise NotImplementedError("x must be provided")
        

    batch_size = y.shape[0]
    start_activity_l = 1 if x is not None else 2
    n_activity_layers = len(activities) - 1
    n_hidden = len(model) - 1


    eL = y - jax.vmap(model[-1])(activities[-2])
    energies = [0.5 * (eL ** 2).sum()]

    for act_l, net_l in zip(
            range(start_activity_l, n_activity_layers),
            range(1, n_hidden)
    ):
        err = activities[act_l] - jax.vmap(model[net_l])(activities[act_l - 1])
        energies.append(0.5 * (err ** 2).sum())


    if x is not None:
        e1 = activities[0] - jax.vmap(model[0])(x)
    else:
        e1 = activities[1] - jax.vmap(model[0])(activities[0])

    energies.append(0.5 * (e1 ** 2).sum())

    total_energy = jnp.array(energies).sum() / batch_size

    if record_layers:
        return jnp.array(energies) / batch_size
    else:
        return total_energy

# %% ../nbs/00_core.ipynb 52
# Version 2. JIT friendly with jax.lax.fori_loop and history recording
def perform_inference(model: List[Callable], activations: List[Array], key, yy: ArrayLike, xx: ArrayLike = None, num_iters: int = 10, lr: float = 0.05, record_history: bool = False, ener_fn: Callable = mse_energy, loss_fn: Callable = mse_energy, inference: bool = True):
    '''
    Perform inference by minimizing energy.
    
    Args:
        record_history: If True, returns (final_activations, energy_history) where energy_history 
                    is an array of shape (num_iters+1, num_layers) containing energies at each iteration.
                    If False, only returns final_activations.
    '''
    # Extract activations by directly passing model layers (no wrapping needed)
    # activations = forward_and_extract_activites(model, x)
    
    def energy_fn(acts):
        return sum(compute_energy(model, acts, key, yy, xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference))
    
    @eqx.filter_jit
    def inference_step(acts):
        new_energy, grads = jax.value_and_grad(energy_fn)(acts)
        return jax.tree.map(lambda a, g: a - lr * g, acts, grads)
    
    if record_history:
        # Preallocate energy history array
        # Shape: (num_iters+1, num_layers)
        num_layers = len(model)
        energy_history = jnp.zeros((num_iters + 1, num_layers))
        
        # Store initial energies at index 0
        initial_energies = jnp.array(compute_energy(model, activations, key, yy, xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference))
        energy_history = energy_history.at[0].set(initial_energies)
        
        # Modified body function that records energies
        def body_fn_with_history(i, state):
            acts, e_hist = state
            new_acts = inference_step(acts)
            # Compute and store energies at iteration i+1
            new_energies = jnp.array(compute_energy(model, new_acts, key, yy, xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference))
            new_e_hist = e_hist.at[i + 1].set(new_energies)
            return new_acts, new_e_hist
        
        # Run loop
        final_acts, energy_history = jax.lax.fori_loop(
            0, num_iters, body_fn_with_history, (activations, energy_history)
        )
        
        return final_acts, energy_history
    else:
        # Original fast version without history
        def body_fn(i, acts):
            return inference_step(acts)
        
        final_acts = jax.lax.fori_loop(0, num_iters, body_fn, activations)
        return final_acts, None

# %% ../nbs/00_core.ipynb 60
def plot_energy_history(history: ArrayLike, len_model, axs = None, title1 = None, title2 = None):
# plot energy history for each layer
    if axs is None:
        fig, axs = plt.subplots(2, 1, figsize=(8, 6))
    else:
        fig = None
        
    for layer_idx in range(len_model - 1):
        axs[0].plot(history[:, layer_idx], label=f'Layer {layer_idx}')
    axs[0].set_xlabel('Iteration')
    axs[0].set_ylabel('Energy')
    axs[0].set_title(title1)
    axs[0].legend()

    for layer_idx in range(len_model):
        axs[1].plot(history[:, layer_idx], label=f'Layer {layer_idx}')
    axs[1].set_xlabel('Iteration')
    axs[1].set_ylabel('Energy')
    axs[1].set_title(title2)
    axs[1].legend()
    
    if fig is not None:
        fig.tight_layout()
        plt.show()
    else:
        return axs

# %% ../nbs/00_core.ipynb 64
def jpc_neg_activity_grad(
        t: float | int,
        activities: PyTree[ArrayLike],
        args: Tuple[
            Tuple[PyTree[Callable], Optional[PyTree[Callable]]],
            ArrayLike,
            Optional[ArrayLike],
        ]
    ) -> PyTree[Array]:
    params, y, x  = args
    
    dFdzs = jax.grad(jpc_pc_energy_fn, argnums=1)(
        params,
        activities,
        y,
        x=x
    )
    return tree_map(lambda dFdz: -dFdz, dFdzs)

# %% ../nbs/00_core.ipynb 69
def jpc_solve_inference(
        params: Tuple[PyTree[Callable], Optional[PyTree[Callable]]],
        activities: PyTree[ArrayLike],
        output: ArrayLike,
        *,
        input: Optional[ArrayLike] = None,
        loss_id: str = "mse",
        param_type: str = "sp",
        solver: AbstractSolver = Heun(),
        max_t1: int = 20,
        dt: float | int = None,
        stepsize_controller: AbstractStepSizeController = PIDController(
            rtol=1e-3, atol=1e-3
        ),
        weight_decay: Scalar = 0.,
        spectral_penalty: Scalar = 0.,
        activity_decay: Scalar = 0.,
        record_iters: bool = False,
        record_every: int = None,
        max_steps: int = 16384
) -> PyTree[Array]:
    if record_every is not None:
        ts = jnp.arange(0, max_t1, record_every)
        saveat = SaveAt(t1=True, ts=ts)
    else:
        saveat = SaveAt(t1=True, steps=record_iters)

    solution = diffeqsolve(
        terms=ODETerm(jpc_neg_activity_grad),
        solver=solver,
        t0=0,
        t1=max_t1,
        dt0=dt,
        y0=activities,
        args=(
            params, 
            output, 
            input, 
        ),
        stepsize_controller=stepsize_controller,
        event=Event(jpc_steady_state_event_with_timeout),  # stop when returning from steady_state_event_with_timeout crosses zero
        saveat=saveat,
        max_steps=max_steps,
        throw=False  # Don't throw errors, just return what we have
    )
    return solution.ys


def jpc_steady_state_event_with_timeout(t, y, args, **kwargs):

    _atol, _rtol = 1e-3, 1e-3
    steady_state_reached = rms_norm(y) < _atol + _rtol * rms_norm(y)
    timeout_reached = jnp.array(t >= 4096, dtype=jnp.bool_)
    return jnp.logical_or(steady_state_reached, timeout_reached)

# %% ../nbs/00_core.ipynb 77
def init_activities_as_ffwd_plus_noise_real(key: PRNGKeyArray, model: List[eqx.Module], xx: ArrayLike, sigma: Scalar = 0.05, inference: bool = True, include_input: bool = True, random_factor: float = 1.0)-> List[Array]:
    """
        add Gaussian noise to forward pass activations and scale it's radius
    """
    
    key, forward_key = jax.random.split(key)
    activations = forward_and_extract_activities(model, xx, key = forward_key, inference=inference)

    random_keys = jax.random.split(key, len(activations))
    random_activities = []
    for act, rand_key in zip(activations, random_keys):
        ran_real = random_factor * sigma * jax.random.normal(rand_key, shape=act.shape) + (1 - random_factor) * act
        ran_act = ran_real
        radii = jnp.linalg.norm(act, axis=-1, keepdims=True)
        ran_act = ran_act / (jnp.linalg.norm(ran_act, axis=-1, keepdims=True) + 1e-12) * radii
        random_activities.append(ran_act)
    if include_input:
        random_activities.insert(0, xx)
    return random_activities

# %% ../nbs/00_core.ipynb 80
@eqx.filter_jit
def pc_training_step(
        model: List[Callable], optimizers: List[optax.GradientTransformation],
        opt_state: List[optax.OptState], key: PRNGKeyArray, yy: ArrayLike, xx: ArrayLike = None, 
        num_inference_iters: int = 10, lr_inference: float = 0.05, ener_fn: Callable = mse_energy, loss_fn: Callable = mse_energy,
        inference_method: str = "BP", record_history = False, feedforward_init: str = "ffwd", 
        sigma: float = 0.05, random_factor: float = 1.0,
        include_input: bool = False, act_amp = None):
    # include_input = False # for supervised learning, but did not implement unsupervised yet
    inference = False # during training, we want dropout to be active
    # key, init_key, inference_key, grad_key, final_key = jax.random.split(key, 5)
    if act_amp == None:
        act_amp = [1.0 for _ in range(len(model))]

    if inference_method == "BP":
        if feedforward_init == "ffwd":
            activations = forward_and_extract_activities(model, xx, key = key, inference=inference)
        elif feedforward_init == "random":
            activations = init_activities_as_ffwd_plus_noise_real(
                key, model, xx, sigma=sigma, inference=inference, include_input=include_input, random_factor = random_factor)
        else:
            raise ValueError(f"Invalid feedforward_init: {feedforward_init}. Choose 'ffwd' or 'random'.")
        fina_acts, energy_history = perform_inference(model, [amp * act for amp, act in zip(act_amp, activations)], key, yy, xx = xx, num_iters=num_inference_iters, lr=lr_inference, record_history= record_history, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference)
    elif inference_method == "ODE":
        activations = jpc_init_activities_with_ffwd(model, xx)
        ode_solution = jpc_solve_inference(
            (model, None), 
            activations, 
            yy, 
            input = xx,
            max_t1 = num_inference_iters,
            # ode slution shape: (num_layers, num_iters, batch_size, layer_dim)
            # expected final activaties shape: (num_layers, batch_size, layer_dim)
            record_every= 1 if record_history else None
        )
        fina_acts = [act[-1] for act in ode_solution]
        if record_history:
            energy_history = []
            for single_iter in range(ode_solution[0].shape[0]):
                current_act = [arr[single_iter] for arr in ode_solution]
                current_energies = compute_energy(model, current_act, key, yy, xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference)
                energy_history.append(current_energies)
            energy_history = jnp.array(energy_history)
        else:
            energy_history = None
    else:
        raise ValueError(f"Invalid inference_method: {inference_method}. Choose 'BP' or 'ODE'.")

    def energy_fn(mdl):
        return sum(compute_energy(mdl, fina_acts, key, yy, xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference))
    
    
    energies, grads = eqx.filter_value_and_grad(energy_fn)(model)
    
    # Create new model list with updated layers
    updated_model = []
    updated_opt_state = []
    
    for i, (layer, optimizer, grad, opt_st) in enumerate(zip(model, optimizers, grads, opt_state)):
        updates, new_opt_st = optimizer.update(grad, opt_st, eqx.filter(layer, eqx.is_array))
        new_layer = eqx.apply_updates(layer, updates)
        updated_model.append(new_layer)
        updated_opt_state.append(new_opt_st)
    
    return {
        'model': updated_model, 
        'opt_state': updated_opt_state, 
        'energies': compute_energy(model, fina_acts, key = key, y = yy, x = xx, ener_fn=ener_fn, loss_fn=loss_fn, inference=True),  # mean to set true
        'grads': grads,
        'energies_history': energy_history  
    }

# %% ../nbs/00_core.ipynb 86
@eqx.filter_jit
def pc_final_inference_BP(
        key: PRNGKeyArray,
        model: List[Callable], yy: ArrayLike, xx: ArrayLike, 
        num_inference_iters: int = 10, lr_inference: float = 0.05, ener_fn: Callable = mse_energy, loss_fn: Callable = mse_energy,
        inference_method: str = "BP", record_history = False,
        inference: bool = True
    ) -> Dict:
    random_activities = init_activities_from_normal_ffwd(
        key, model, input_shape = xx.shape, sigma=0.05, inference=inference
    )
    if inference_method == "BP":
        fina_acts, final_energy_history = perform_inference(model, random_activities, key= key, yy=yy, xx = None, num_iters=num_inference_iters, lr=lr_inference, record_history= record_history, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference)
    
    else:
        raise ValueError(f"Invalid inference_method: {inference_method}. Choose 'BP' or 'ODE'.")
    
    return{
        'activities': fina_acts,
        'energy_history': final_energy_history
    }
    
    

def pc_final_inference_ODE(
        key: PRNGKeyArray,
        model: List[Callable], y: ArrayLike, x: ArrayLike, 
        num_inference_iters: int = 10, lr_inference: float = 0.05, ener_fn: Callable = mse_energy, loss_fn: Callable = mse_energy,
        inference_method: str = "ODE", record_history = False
    ) -> Dict:
    random_activities = init_activities_from_normal_ffwd(
        key, model, input_shape = x.shape, sigma=0.05
    )

    if inference_method == "ODE":
        ode_solution = jpc_solve_inference(
            (model, None), 
            random_activities, 
            y, 
            input = None,
            max_t1 = num_inference_iters,
            # ode slution shape: (num_layers, num_iters, batch_size, layer_dim)
            # expected final activaties shape: (num_layers, batch_size, layer_dim)
            record_every= 1
        )
        fina_acts = [act[-1] for act in ode_solution]
        if record_history:
            final_energy_history = []
            for single_iter in range(ode_solution[0].shape[0]):
                current_act = [arr[single_iter] for arr in ode_solution]
                current_energies = compute_energy(model, current_act, y, None, ener_fn=ener_fn, loss_fn=loss_fn)
                final_energy_history.append(current_energies)
            final_energy_history = jnp.array(final_energy_history)
            final_energy_history = final_energy_history[~jnp.isnan(final_energy_history).all(axis=1)]
        else:
            final_energy_history = None
    else:
        raise ValueError(f"Invalid inference_method: {inference_method}. Choose 'BP' or 'ODE'.")
    
    return{
        'activities': fina_acts,
        'energy_history': final_energy_history
    }
    
    


# %% ../nbs/00_core.ipynb 91
def validate_generation(model: List[Callable], data_loader, num_inference_iters: int = 1000, lr_inference: float = 1, inference_method: str = "BP", record_history: bool = False, ener_fn:Callable = mse_energy, loss_fn:Callable = mse_energy):
    key = jax.random.PRNGKey(0)
    inference = True  # during validation, we want dropout to be disabled
    total_loss = 0.0
    # num_batches = 0
    pred_labels = []
    true_labels = []
    # pred_imgs = []
    energy_history = False
    for idx, (images, labels) in tqdm(enumerate(data_loader), total=len(data_loader), leave=False, desc="Generation Inference"):
        # Convert torch tensors to jax arrays
        x = jnp.array(labels.numpy())
        y = jnp.array(images.numpy())
        if inference_method == "BP":
            final_rst = pc_final_inference_BP(
                key, model, yy = y, xx = x,  # will be set to None inside
                num_inference_iters=num_inference_iters, lr_inference=lr_inference, inference_method=inference_method, record_history=record_history, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference
            )
        elif inference_method == "ODE":
            final_rst = pc_final_inference_ODE(
                key, model, y = y, x = x,  # will be set to None inside
                num_inference_iters=num_inference_iters, lr_inference=lr_inference, inference_method=inference_method, record_history=record_history, ener_fn=ener_fn, loss_fn=loss_fn, inference=inference
            )

        # preded_imgs = final_rst['activities'][-1]
        first_act = final_rst['activities'][0].argmax(axis=-1)
        pred_labels.append(first_act)
        true_labels.append(x.argmax(axis=-1))
        if record_history == True:
            if idx == 0:
                energy_history = final_rst['energy_history']
            else:
                energy_history += final_rst['energy_history']
    # just select first 16 images to visualize
    
    model_output = one_step_forward(model, x, key = key, inference=inference)[:16].reshape(16, 1, 28, 28)
    fig, axs = plt.subplots(4, 4, figsize=(6, 6))
    for i, ax in enumerate(axs.flatten()):
        ax.imshow(model_output[i].squeeze(), cmap='gray')
        ax.set_title(f'{x[i].argmax()}')
        ax.axis('off')
    fig.tight_layout()
    plt.show()

    if record_history ==True:
        energy_history = energy_history / len(data_loader)
        plot_energy_history(energy_history, len(model), axs=None,
            title1 = 'Generation Inference Energy History',
            title2 = 'Generation Inference Energy History'
            )
    pred_labels = jnp.concatenate(pred_labels)
    true_labels = jnp.concatenate(true_labels)
    acc = jnp.mean(pred_labels == true_labels)
    print(f'Generation Accuracy: {acc:.4f}')
