"""Prepare datasets and dataloaders"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_creator.ipynb.

# %% auto 0
__all__ = ['one_hot', 'MNIST', 'FashionMNIST', 'CombinedMNIST', 'CIFAR10', 'preprocess_audio', 'get_speech_classes',
        'label_to_onehot', 'SPEECHCOMMANDS', 'get_mnist_loaders', 'get_cifar10_loaders',
        'get_speechcommands_loaders', 'get_combined_loaders', 'plot_imgs', 'plot_mnist_imgs']

# %% ../nbs/01_data_creator.ipynb 2
import os
import pickle
import warnings
from pathlib import Path
import matplotlib.pyplot as plt
import equinox as eqx
import equinox.nn as nn
import jax
import jax.numpy as jnp
import numpy as np
import optax
import torch
import torchaudio
from torch.utils.data import Dataset, DataLoader, Subset
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
import IPython.display as ipd
# if is called in a notebook, use tqdm.notebook

from IPython import get_ipython

if get_ipython() is not None:
    from tqdm.notebook import tqdm
else:
    from tqdm import tqdm



# %% ../nbs/01_data_creator.ipynb 4
def one_hot(labels, n_classes=10):
    arr = torch.eye(n_classes)
    return arr[labels]


class MNIST(datasets.MNIST):
    def __init__(self, train, normalise=True, save_dir="../data", total_classes=10):
        self.total_classes = total_classes
        if normalise:
            transform = transforms.Compose(
                [
                    transforms.ToTensor(),
                    transforms.Normalize(
                        mean=(0.1307), std=(0.3081)
                    )
                ]
            )
        else:
            transform = transforms.Compose([transforms.ToTensor()])
        super().__init__(save_dir, download=True, train=train, transform=transform)

    def __getitem__(self, index):
        img, label = super().__getitem__(index)
        img = torch.flatten(img)
        label = one_hot(label, n_classes=self.total_classes)
        return img, label


# %% ../nbs/01_data_creator.ipynb 8
class FashionMNIST(datasets.FashionMNIST):
    def __init__(self, train, normalise=True, save_dir="../data", total_classes=10):
        self.total_classes = total_classes
        if normalise:
            transform = transforms.Compose(
                [
                    transforms.ToTensor(),
                    transforms.Normalize(
                        mean=(0.1307), std=(0.3081)
                    )
                ]
            )
        else:
            transform = transforms.Compose([transforms.ToTensor()])
        super().__init__(save_dir, download=True, train=train, transform=transform)

    def __getitem__(self, index):
        img, label = super().__getitem__(index)
        img = torch.flatten(img)
        label = one_hot(label, n_classes=self.total_classes)
        return img, label

# %% ../nbs/01_data_creator.ipynb 12
class CombinedMNIST(Dataset):
    """Combined MNIST and FashionMNIST dataset with 20 classes total.
    MNIST classes: 0-9
    FashionMNIST classes: 10-19
    """
    def __init__(self, train, normalise=True, save_dir="../data", label_compress = False, total_classes=20):
        self.mnist = MNIST(train=train, normalise=normalise, save_dir=save_dir, total_classes=total_classes)
        self.fashionmnist = FashionMNIST(train=train, normalise=normalise, save_dir=save_dir, total_classes=total_classes)
        self.mnist_len = len(self.mnist)
        self.fashion_len = len(self.fashionmnist)
        self.total_len = self.mnist_len + self.fashion_len
        self.label_compress = label_compress
        self.total_classes = total_classes
        
    def __len__(self):
        return self.total_len
    
    def __getitem__(self, index):
        if index < self.mnist_len:
            # Get from MNIST (classes 0-9)
            img, label = self.mnist[index]
            return img, label
        else:
            # Get from FashionMNIST (classes 10-19)
            img, label = self.fashionmnist[index - self.mnist_len]
            # Shift labels by 10 to make them classes 10-19
            label_idx = 10 if self.label_compress else torch.argmax(label).item() + 10
            label = one_hot(label_idx, n_classes=self.total_classes)
            return img, label

# %% ../nbs/01_data_creator.ipynb 16
class CIFAR10(datasets.CIFAR10):
    def __init__(self, train, normalise=True, save_dir="../data"):
        if normalise:
            transform = transforms.Compose(
                [
                    transforms.ToTensor(),
                    transforms.Normalize(
                        mean=(0.4914, 0.4822, 0.4465),
                        std=(0.2023, 0.1994, 0.2010)
                    )
                ]
            )
        else:
            transform = transforms.Compose([transforms.ToTensor()])
        super().__init__(save_dir, download=True, train=train, transform=transform)

    def __getitem__(self, index):
        img, label = super().__getitem__(index)
        img = torch.flatten(img)
        label = one_hot(label, n_classes=10)
        return img, label

# %% ../nbs/01_data_creator.ipynb 20
def preprocess_audio(waveform, sample_rate, target_sample_rate=16000, max_length=16000, normalise=True):
    """Preprocess audio waveform to standardized format."""
    # Resample if necessary
    if sample_rate != target_sample_rate:
        resampler = torchaudio.transforms.Resample(sample_rate, target_sample_rate)
        waveform = resampler(waveform)
    
    # Convert to mono if stereo
    if waveform.shape[0] > 1:
        waveform = torch.mean(waveform, dim=0, keepdim=True)
    
    # Pad or truncate to fixed length
    if waveform.shape[1] < max_length:
        padding = max_length - waveform.shape[1]
        waveform = torch.nn.functional.pad(waveform, (0, padding))
    else:
        waveform = waveform[:, :max_length]
    
    # Flatten the waveform
    waveform = torch.flatten(waveform)
    
    # Normalize if requested
    if normalise:
        std = waveform.std()
        if std > 1e-8:
            waveform = (waveform - waveform.mean()) / std
        else:
            waveform = waveform - waveform.mean()
    
    return waveform


def get_speech_classes():
    """Get standard speech commands classes."""
    # return ["yes", "no", "up", "down", "left", "right", "on", "off", "stop", "go", "backward", "silence", 'five']
    return ['backward', 'bed', 'bird', 'cat', 'dog', 'down', 'eight', 'five',
        'follow', 'forward', 'four', 'go', 'happy', 'house', 'learn',
        'left', 'marvin', 'nine', 'no', 'off', 'on', 'one', 'right',
        'seven', 'sheila', 'six', 'stop', 'three', 'tree', 'two', 'up',
        'visual', 'wow', 'yes', 'zero']

def label_to_onehot(label, classes):
    """Convert string label to one-hot encoding."""
    class_to_idx = {cls: idx for idx, cls in enumerate(classes)}
    
    if label in class_to_idx:
        label_idx = class_to_idx[label]
    else:
        print(f"Warning: label '{label}' not in known classes. Assigning to 'unknown'.")
        label_idx = class_to_idx["unknown"]
    
    return one_hot(torch.tensor(label_idx), n_classes=len(classes))


class SPEECHCOMMANDS(torchaudio.datasets.SPEECHCOMMANDS):
    def __init__(self, train, normalise=True, save_dir="../data", sample_rate=16000, max_length=16000):
        subset = "training" if train else "testing"
        super().__init__(save_dir, download=True, subset=subset)
        self.normalise = normalise
        self.sample_rate = sample_rate
        self.max_length = max_length
        self.classes = get_speech_classes()

    def __getitem__(self, index):
        waveform, sample_rate, label, speaker_id, utterance_number = super().__getitem__(index)
        
        # Preprocess audio
        waveform = preprocess_audio(
            waveform, sample_rate, self.sample_rate, self.max_length, self.normalise
        )
        
        # Convert label to one-hot
        label_onehot = label_to_onehot(label, self.classes)
        
        return waveform, label_onehot


# %% ../nbs/01_data_creator.ipynb 27
def get_mnist_loaders(batch_size):
    train_data = MNIST(train=True, normalise=True)
    test_data = MNIST(train=False, normalise=True)
    train_loader = DataLoader(
        dataset=train_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    test_loader = DataLoader(
        dataset=test_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    return train_loader, test_loader


def get_cifar10_loaders(batch_size):
    train_data = CIFAR10(train=True, normalise=True)
    test_data = CIFAR10(train=False, normalise=True)
    train_loader = DataLoader(
        dataset=train_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    test_loader = DataLoader(
        dataset=test_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    return train_loader, test_loader


def get_speechcommands_loaders(batch_size, sample_rate=16000, max_length=16000):
    with open(f'../sub_path_idx/speechcommands_subset_idx_0.pkl', 'rb') as f:
        train_subset_idx = pickle.load(f)
    with open(f'../sub_path_idx/speechcommands_subset_idx_1.pkl', 'rb') as f:
        test_subset_idx = pickle.load(f)

    train_data = SPEECHCOMMANDS(train=True, normalise=True, sample_rate=sample_rate, max_length=max_length)
    train_data = Subset(train_data, train_subset_idx)
    test_data = SPEECHCOMMANDS(train=False, normalise=True, sample_rate=sample_rate, max_length=max_length)
    test_data = Subset(test_data, test_subset_idx)
    print(f'[CAVEAT] Only using subset of SpeechCommands dataset which has 10 classes with 1000 training samples and 100 test samples each.')
    train_loader = DataLoader(
        dataset=train_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    test_loader = DataLoader(
        dataset=test_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    return train_loader, test_loader


def get_combined_loaders(batch_size, label_compress = False, total_classes=20):
    train_data = CombinedMNIST(train=True, normalise=True, label_compress=label_compress, total_classes=total_classes)
    test_data = CombinedMNIST(train=False, normalise=True, label_compress=label_compress, total_classes=total_classes)
    train_loader = DataLoader(
        dataset=train_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    test_loader = DataLoader(
        dataset=test_data,
        batch_size=batch_size,
        shuffle=True,
        drop_last=True
    )
    return train_loader, test_loader

# %% ../nbs/01_data_creator.ipynb 31
def plot_imgs(imgs, labels, n_imgs=16, dataset_type="MNIST"):
    """Plot images from different datasets."""
    rows = np.sqrt(n_imgs).astype(int)
    cols = int(np.ceil(n_imgs / rows))

    fig, axs = plt.subplots(rows, cols, figsize=(cols * 2, rows * 2))
    axs = axs.flatten()
    
    for i in range(n_imgs):
        ax = axs[i]
        ax.set_xticks([])
        ax.set_yticks([])
        ax.grid(False)
        
        if dataset_type == "MNIST":
            # MNIST: 784 -> 28x28, grayscale
            ax.imshow(imgs[i].reshape(28, 28), cmap=plt.cm.binary_r)
        elif dataset_type == "CIFAR10":
            _mean = np.array([0.4914, 0.4822, 0.4465]).reshape(3, 1, 1)
            _std = np.array([0.2023, 0.1994, 0.2010]).reshape(3, 1, 1)
            img = imgs[i].reshape(3, 32, 32) * _std + _mean  # Unnormalize
            img = img.transpose(1, 2, 0)  # Convert from CHW to HWC
            # Clip values to valid range and convert to uint8 for display
            img = (img - img.min()) / (img.max() - img.min())  # Normalize to [0, 1]
            img = np.clip(img, 0, 1)
            ax.imshow(np.asarray(img))
            
        elif dataset_type == "SPEECHCOMMANDS":
            # SPEECHCOMMANDS: 16000 -> 1D waveform, plot as time series
            # ax.plot(imgs[i])
            # ax.set_title(f'Waveform')
            # ax.set_xlabel('Sample')
            # ax.set_ylabel('Amplitude')
            # plot the signal after fft
            fft_spectrum = np.fft.fft(imgs[i])
            freq = np.fft.fftfreq(len(fft_spectrum))
            ax.plot(freq[:len(freq)//2], np.abs(fft_spectrum)[:len(fft_spectrum)//2])
            fig.suptitle(f'FFT Spectrum')
            
        # else:
        #     # Fallback: try to detect format based on size
        #     if imgs[i].shape[0] == 784:
        #         ax.imshow(imgs[i].reshape(28, 28), cmap=plt.cm.binary_r)
        #     elif imgs[i].shape[0] == 3072:
        #         img = imgs[i].reshape(32, 32, 3)
        #         img = np.clip(img, 0, 1)
        #         ax.imshow(img)
        #     elif imgs[i].shape[0] == 16000:
        #         # Likely audio data
        #         ax.plot(imgs[i])
        #         ax.set_title(f'Waveform')
        #         ax.set_xlabel('Sample')
        #         ax.set_ylabel('Amplitude')
        #     else:
        #         # Can't determine format, skip plotting
        #         ax.text(0.5, 0.5, 'Unknown\nformat', ha='center', va='center', 
        #             transform=ax.transAxes)

        ax.set_xlabel(np.asarray(jnp.argmax(labels, axis=1)[i]))
        fig.tight_layout()
    return fig


def plot_mnist_imgs(imgs, labels, n_imgs=16):
    """Legacy function for backward compatibility - auto-detects dataset format."""
    # Auto-detect dataset type based on image dimensions
    if imgs[0].shape[0] == 784:
        dataset_type = "MNIST"
    elif imgs[0].shape[0] == 3072:
        dataset_type = "CIFAR10"
    elif imgs[0].shape[0] == 16000:
        dataset_type = "SPEECHCOMMANDS"
    else:
        dataset_type = "auto"  # Let plot_imgs handle unknown formats
    
    return plot_imgs(imgs, labels, n_imgs, dataset_type=dataset_type)
