name: Build docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install '.[docs]'
          # Force correct versions of jax & jaxlib
          python -m pip install --force-reinstall --no-cache-dir "jax[cpu]==0.6.1" jaxlib==0.6.1
          # Remove any stale .pyc files or cached builds
          find . -type d -name __pycache__ -exec rm -rf {} +
          find . -name "*.pyc" -delete
      
      - name: Check jaxlib import and version
        run: |
          python -c "import jaxlib; print('jaxlib version:', jaxlib.__version__)"
          python -c "import jaxlib.xla_extension as xla; print('xla extension loaded')"

      - name: Check installed packages
        run: pip list

      - name: Build docs
        run: |
          mkdocs build

      - name: Deploy docs
        run: mkdocs gh-deploy --force