name: Build docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install '.[docs]'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo-dev libffi-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y jaxlib
          pip install "jaxlib[cpu]==0.6.1"
          python -m pip install '.[docs]'
      
      - name: Debug JAXlib installation
        run: |
          echo "Python version:"
          python --version
          echo "Platform:"
          uname -a
          echo "Installing jax and jaxlib..."
          pip install jax jaxlib --verbose
          echo "Installed packages:"
          pip list
          echo "Testing import..."
          python -c "import jax; print('JAX version:', jax.__version__)"
      
      - name: Debug env before docs build
        run: |
          export LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.11.12/x64/lib:$LD_LIBRARY_PATH
          echo $LD_LIBRARY_PATH
          python -c "import jax; print('JAX version:', jax.__version__)"
          mkdocs build
      
      - name: Build docs
        run: |
          mkdocs build

      - name: Deploy docs
        run: mkdocs gh-deploy --force